
sudo: required
services:
  - docker

before_install:
  - docker build -t venwarrior/docker-react-travis -f Dockerfile.dev .

script:
  - docker run venwarrior/docker-react-travis npm run test -- --coverage